--------------------------------------------------------------------------------
-- 20_them_co_cau_to_chuc.sql
-- Mở rộng lược đồ để biểu diễn cơ cấu tổ chức của công ty.
-- Chạy bằng tài khoản TASK_APP trên PDB XEPDB1.
--
-- VÌ SAO CẦN
-- Lược đồ 7 bảng ban đầu chỉ có hai vai trò MANAGER/EMPLOYEE và không có khái niệm
-- phòng ban. Với lược đồ đó, AI gợi ý phải quét toàn bộ nhân viên công ty — một nhân
-- viên phòng hành chính vẫn lọt vào danh sách gợi ý cho nhiệm vụ sửa lỗi backend,
-- chỉ vì mô tả kỹ năng tình cờ trùng vài từ.
--
-- BỔ SUNG (toàn bộ là THÊM MỚI, không DROP bảng nào, không mất dữ liệu):
--   1. Bảng DEPARTMENTS          — phòng ban
--   2. Bảng USER_QUALIFICATIONS  — bằng cấp, chuyên ngành
--   3. USERS.DEPARTMENT_ID       — người này thuộc phòng nào
--   4. USERS.MANAGER_ID          — ai quản người này (tự tham chiếu, dựng cây tổ chức)
--   5. USERS.JOB_TITLE           — chức danh hiển thị
--   6. TASKS.DEPARTMENT_ID       — nhiệm vụ này thuộc phòng nào
--   7. Mở rộng CK_USERS_ROLE từ 2 lên 4 giá trị
--
-- Các cột mới đều NULL được, nên dữ liệu đang có vẫn hợp lệ ngay sau khi chạy.
--
-- CHẠY LẠI ĐƯỢC nhiều lần: mọi lệnh đều bọc trong khối bắt lỗi "đã tồn tại".
--------------------------------------------------------------------------------

SET DEFINE OFF

--==============================================================================
-- Tiện ích: chạy một lệnh DDL, bỏ qua nếu đối tượng đã tồn tại
--==============================================================================
DECLARE
    PROCEDURE chay(p_lenh VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE p_lenh;
    EXCEPTION
        WHEN OTHERS THEN
            -- -955  : tên đã được đối tượng khác dùng (bảng/index đã có)
            -- -1430 : cột đã tồn tại trong bảng
            -- -2260 : bảng đã có khoá chính
            -- -2275 : ràng buộc khoá ngoại đã tồn tại
            -- -1442 : cột đã NOT NULL
            -- -1408 : danh sách cột này đã được đánh index
            IF SQLCODE NOT IN (-955, -1430, -2260, -2275, -1442, -1408) THEN
                RAISE;
            END IF;
    END;
BEGIN
    ----------------------------------------------------------------------------
    -- 1. DEPARTMENTS — phòng ban
    ----------------------------------------------------------------------------
    chay('
        CREATE TABLE DEPARTMENTS (
            ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            CODE         VARCHAR2(30 CHAR)  NOT NULL,
            NAME         VARCHAR2(150 CHAR) NOT NULL,
            DESCRIPTION  VARCHAR2(500 CHAR),
            CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UPDATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT UQ_DEPARTMENTS_CODE UNIQUE (CODE)
        )');

    ----------------------------------------------------------------------------
    -- 2. USERS — ba cột mới
    --
    -- MANAGER_ID tự tham chiếu chính USERS. Chỉ một cột này là đủ dựng cả bốn cấp
    -- Giám đốc -> Trưởng phòng -> Leader -> Nhân viên, không cần thêm bảng TEAMS.
    ----------------------------------------------------------------------------
    chay('ALTER TABLE USERS ADD (DEPARTMENT_ID NUMBER)');
    chay('ALTER TABLE USERS ADD (MANAGER_ID    NUMBER)');
    chay('ALTER TABLE USERS ADD (JOB_TITLE     VARCHAR2(100 CHAR))');

    chay('ALTER TABLE USERS ADD CONSTRAINT FK_USERS_DEPARTMENT
              FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID)');
    chay('ALTER TABLE USERS ADD CONSTRAINT FK_USERS_MANAGER
              FOREIGN KEY (MANAGER_ID) REFERENCES USERS(ID)');

    ----------------------------------------------------------------------------
    -- 3. USER_QUALIFICATIONS — bằng cấp
    --
    -- Tách khỏi USER_SKILLS vì hai thứ khác bản chất: bằng cấp là chứng nhận đào tạo
    -- chính quy (kiểm chứng được), kỹ năng là mức thành thạo tự khai và thay đổi liên tục.
    -- AI dùng cả hai với trọng số khác nhau.
    ----------------------------------------------------------------------------
    chay('
        CREATE TABLE USER_QUALIFICATIONS (
            ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            USER_ID      NUMBER NOT NULL,
            DEGREE_NAME  VARCHAR2(150 CHAR) NOT NULL,
            MAJOR        VARCHAR2(150 CHAR) NOT NULL,
            DEGREE_LEVEL VARCHAR2(30 CHAR),
            SCHOOL       VARCHAR2(200 CHAR),
            GRAD_YEAR    NUMBER(4),
            CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UPDATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT FK_QUALIFICATIONS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
            CONSTRAINT CK_QUALIFICATIONS_LEVEL CHECK (
                DEGREE_LEVEL IS NULL OR DEGREE_LEVEL IN
                (''TRUNG_CAP'', ''CAO_DANG'', ''DAI_HOC'', ''THAC_SI'', ''TIEN_SI'', ''CHUNG_CHI'')
            ),
            CONSTRAINT CK_QUALIFICATIONS_YEAR CHECK (
                GRAD_YEAR IS NULL OR GRAD_YEAR BETWEEN 1950 AND 2100
            )
        )');

    ----------------------------------------------------------------------------
    -- 4. TASKS.DEPARTMENT_ID — nhiệm vụ thuộc phòng nào
    --
    -- Đây là cột then chốt của phần AI: nó cho phép LOẠI CỨNG mọi người ngoài phòng
    -- trước khi chấm điểm, thay vì để họ lọt vào rồi mới trừ điểm.
    ----------------------------------------------------------------------------
    chay('ALTER TABLE TASKS ADD (DEPARTMENT_ID NUMBER)');
    chay('ALTER TABLE TASKS ADD CONSTRAINT FK_TASKS_DEPARTMENT
              FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID)');

    ----------------------------------------------------------------------------
    -- 5. Index cho các khoá ngoại mới
    -- Oracle không tự tạo index cho khoá ngoại. Thiếu thì truy vấn "người trong phòng X"
    -- phải quét toàn bảng, và bảng cha bị khoá khi cập nhật.
    ----------------------------------------------------------------------------
    chay('CREATE INDEX IDX_USERS_DEPARTMENT_ID    ON USERS (DEPARTMENT_ID)');
    chay('CREATE INDEX IDX_USERS_MANAGER_ID       ON USERS (MANAGER_ID)');
    chay('CREATE INDEX IDX_QUALIFICATIONS_USER_ID ON USER_QUALIFICATIONS (USER_ID)');
    chay('CREATE INDEX IDX_TASKS_DEPARTMENT_ID    ON TASKS (DEPARTMENT_ID)');
    -- Đường truy cập nóng nhất của AI: lọc người theo phòng rồi theo vai trò.
    chay('CREATE INDEX IDX_USERS_DEPT_ROLE        ON USERS (DEPARTMENT_ID, USER_ROLE)');
END;
/

--==============================================================================
-- 6. Mở rộng CK_USERS_ROLE từ 2 lên 4 giá trị
--
-- Đây là thao tác DUY NHẤT sửa thứ đang có. Phải xoá ràng buộc cũ rồi tạo lại vì
-- Oracle không cho sửa trực tiếp biểu thức CHECK.
--
-- Dữ liệu hiện có (MANAGER/EMPLOYEE) vẫn nằm trong tập giá trị mới nên không dòng nào
-- vi phạm. Bốn cấp mới:
--   DIRECTOR   Giám đốc      — quản toàn công ty, giao việc mọi phòng
--   DEPT_HEAD  Trưởng phòng  — quản một phòng, giao việc trong phòng mình
--   TEAM_LEAD  Trưởng nhóm   — quản một nhóm, vừa giao vừa nhận việc
--   EMPLOYEE   Nhân viên     — nhận việc
--==============================================================================
DECLARE
    v_dem NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_dem FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'USERS' AND CONSTRAINT_NAME = 'CK_USERS_ROLE';

    IF v_dem > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE USERS DROP CONSTRAINT CK_USERS_ROLE';
    END IF;

    EXECUTE IMMEDIATE '
        ALTER TABLE USERS ADD CONSTRAINT CK_USERS_ROLE CHECK (
            USER_ROLE IN (''DIRECTOR'', ''DEPT_HEAD'', ''TEAM_LEAD'', ''EMPLOYEE'',
                          ''MANAGER'')
        )';
    -- MANAGER vẫn được giữ trong danh sách hợp lệ để dữ liệu cũ không vỡ giữa chừng.
    -- Script seed sẽ chuyển hết sang bốn giá trị mới; sau đó có thể bỏ MANAGER đi.
END;
/

COMMIT;

--==============================================================================
-- KIỂM CHỨNG
--==============================================================================
SET PAGESIZE 100 LINESIZE 200

PROMPT === Bảng sau khi mở rộng ===
SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME;

PROMPT === Cột mới của USERS ===
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
FROM   USER_TAB_COLUMNS
WHERE  TABLE_NAME = 'USERS' AND COLUMN_NAME IN ('DEPARTMENT_ID','MANAGER_ID','JOB_TITLE');

PROMPT === Cột mới của TASKS ===
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
FROM   USER_TAB_COLUMNS
WHERE  TABLE_NAME = 'TASKS' AND COLUMN_NAME = 'DEPARTMENT_ID';

PROMPT === Ràng buộc vai trò ===
SELECT SEARCH_CONDITION_VC FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CK_USERS_ROLE';

PROMPT === Dữ liệu cũ còn nguyên ===
SELECT 'USERS=' || (SELECT COUNT(*) FROM USERS) ||
       ' TASKS=' || (SELECT COUNT(*) FROM TASKS) ||
       ' SKILLS=' || (SELECT COUNT(*) FROM USER_SKILLS) AS CON_NGUYEN
FROM DUAL;
