--------------------------------------------------------------------------------
-- 23_nang_cap_v2.sql
-- Nâng lược đồ lên V2 theo tài liệu thiết kế: nhóm trong phòng ban, danh mục kỹ năng
-- chuẩn hoá, kỹ năng yêu cầu của nhiệm vụ, điểm đánh giá kết quả.
-- Chạy bằng tài khoản TASK_APP trên PDB XEPDB1, SAU 20_them_co_cau_to_chuc.sql.
--
-- NGUYÊN TẮC: CHỈ MỞ RỘNG, KHÔNG THU HẸP
--   Chỉ thêm bảng, thêm cột, thêm ràng buộc. Không DROP, không đổi tên, không xoá
--   dữ liệu. Mọi cột mới đều cho phép NULL nên code cũ vẫn chạy ngay sau khi áp dụng.
--   Bước thu hẹp (bỏ USER_SKILLS.SKILL_NAME, bỏ USERS.MANAGER_ID) để dành cho một
--   script sau, chỉ chạy khi ứng dụng đã chạy ổn trên lược đồ mới.
--
-- BỔ SUNG
--   Bảng mới     TEAMS, SKILLS, TASK_REQUIRED_SKILLS
--   USERS        + TEAM_ID, HIRED_DATE
--   USER_SKILLS  + SKILL_ID, YEARS_EXPERIENCE
--   TASKS        + TEAM_ID, ESTIMATED_EFFORT
--   TASK_REPORTS + QUALITY_SCORE, COMPLETION_SCORE
--   DEPARTMENTS  + HEAD_USER_ID
--   CK_USERS_ROLE bỏ giá trị cũ MANAGER
--
-- LỆCH SO VỚI BẢN THIẾT KẾ: KHÔNG ĐỔI TÊN USER_ROLE VÀ USER_QUALIFICATIONS
--   Bản thiết kế đề xuất đổi thành SYSTEM_ROLE và USER_EDUCATIONS. Khi làm thì thấy
--   cái giá không đáng: script 20 và 21 dùng tên cũ, đổi tên là chuỗi dựng lại dữ
--   liệu demo gãy, trong khi lợi ích chỉ là tên gọi. Hai khái niệm vẫn tách bạch:
--   USER_ROLE là QUYỀN TRONG HỆ THỐNG, JOB_TITLE là CHỨC DANH TRONG TỔ CHỨC.
--
-- NHÓM PHẢI THUỘC ĐÚNG PHÒNG
--   USERS và TASKS có thêm khoá ngoại ghép (DEPARTMENT_ID, TEAM_ID) trỏ về
--   TEAMS(DEPARTMENT_ID, ID). Nhờ vậy database tự từ chối trường hợp một người hoặc
--   một nhiệm vụ thuộc phòng Nhân sự mà lại gắn nhóm Backend. Phần lọc ứng viên của AI
--   dựa vào hai cột này, nên chúng không được phép mâu thuẫn nhau.
--   Khi TEAM_ID rỗng thì khoá ghép không kiểm, nên người không thuộc nhóm nào vẫn hợp lệ.
--
-- CHẠY LẠI ĐƯỢC: mọi lệnh bọc trong khối bỏ qua lỗi "đã tồn tại".
--------------------------------------------------------------------------------

SET DEFINE OFF

DECLARE
    PROCEDURE chay(p_lenh VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE p_lenh;
    EXCEPTION
        WHEN OTHERS THEN
            -- -955  : tên đã được đối tượng khác dùng (bảng, index đã có)
            -- -1430 : cột đã tồn tại
            -- -2260 : bảng đã có khoá chính
            -- -2261 : đã có ràng buộc UNIQUE hoặc khoá chính trên đúng các cột này
            -- -2264 : tên ràng buộc đã được dùng
            -- -2275 : ràng buộc khoá ngoại này đã tồn tại
            -- -1408 : danh sách cột này đã được đánh index
            IF SQLCODE NOT IN (-955, -1430, -2260, -2261, -2264, -2275, -1408) THEN
                RAISE;
            END IF;
    END;
BEGIN
    ----------------------------------------------------------------------------
    -- 1. SKILLS — danh mục kỹ năng chuẩn hoá
    --
    -- Giải quyết việc cùng một kỹ năng mà mỗi người khai một kiểu: C#, C Sharp,
    -- .NET C#... Tất cả quy về một CODE. DESCRIPTION là phần mô hình nhúng đọc để
    -- hiểu kỹ năng, nên viết theo kiểu liệt kê việc cụ thể.
    ----------------------------------------------------------------------------
    chay('
        CREATE TABLE SKILLS (
            ID           NUMBER GENERATED BY DEFAULT AS IDENTITY,
            CODE         VARCHAR2(50 CHAR)  NOT NULL,
            NAME         VARCHAR2(150 CHAR) NOT NULL,
            CATEGORY     VARCHAR2(30 CHAR)  NOT NULL,
            DESCRIPTION  VARCHAR2(500 CHAR),
            CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UPDATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT PK_SKILLS PRIMARY KEY (ID),
            CONSTRAINT UQ_SKILLS_CODE UNIQUE (CODE),
            CONSTRAINT UQ_SKILLS_NAME UNIQUE (NAME),
            CONSTRAINT CK_SKILLS_CATEGORY CHECK (CATEGORY IN
                (''BACKEND'', ''FRONTEND'', ''DATA'', ''TESTING'',
                 ''MANAGEMENT'', ''HR'', ''ACCOUNTING'', ''ADMIN''))
        )');

    ----------------------------------------------------------------------------
    -- 2. TEAMS — nhóm trong phòng ban
    --
    -- UQ_TEAMS_DEPT_ID trông thừa vì ID đã là khoá chính, nhưng nó bắt buộc phải có:
    -- khoá ngoại ghép (DEPARTMENT_ID, TEAM_ID) ở USERS và TASKS cần một khoá duy nhất
    -- đúng hai cột đó để trỏ vào.
    --
    -- Hai ràng buộc UNIQUE đều bắt đầu bằng DEPARTMENT_ID nên đã kiêm luôn index cho
    -- khoá ngoại FK_TEAMS_DEPARTMENT.
    ----------------------------------------------------------------------------
    chay('
        CREATE TABLE TEAMS (
            ID              NUMBER GENERATED BY DEFAULT AS IDENTITY,
            DEPARTMENT_ID   NUMBER NOT NULL,
            CODE            VARCHAR2(30 CHAR)  NOT NULL,
            NAME            VARCHAR2(150 CHAR) NOT NULL,
            DESCRIPTION     VARCHAR2(500 CHAR),
            LEADER_USER_ID  NUMBER,
            CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT PK_TEAMS PRIMARY KEY (ID),
            CONSTRAINT UQ_TEAMS_DEPT_CODE UNIQUE (DEPARTMENT_ID, CODE),
            CONSTRAINT UQ_TEAMS_DEPT_ID   UNIQUE (DEPARTMENT_ID, ID),
            CONSTRAINT FK_TEAMS_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID)
                REFERENCES DEPARTMENTS(ID),
            CONSTRAINT FK_TEAMS_LEADER FOREIGN KEY (LEADER_USER_ID)
                REFERENCES USERS(ID) ON DELETE SET NULL
        )');
    chay('CREATE INDEX IDX_TEAMS_LEADER_USER_ID ON TEAMS (LEADER_USER_ID)');

    ----------------------------------------------------------------------------
    -- 3. TASK_REQUIRED_SKILLS — nhiệm vụ đòi hỏi kỹ năng gì
    --
    -- SOURCE phân biệt kỹ năng do AI tự trích từ mô tả (AI) với kỹ năng người giao
    -- nhập tay (MANUAL). Nhờ đó đo được AI trích đúng bao nhiêu phần trăm.
    --
    -- ON DELETE CASCADE vì ứng dụng CÓ xoá nhiệm vụ ở trạng thái MOI_TAO, và đó đúng
    -- là lúc AI vừa trích kỹ năng xong. Không cascade thì xoá nhiệm vụ sẽ vướng ORA-02292.
    ----------------------------------------------------------------------------
    chay('
        CREATE TABLE TASK_REQUIRED_SKILLS (
            ID              NUMBER GENERATED BY DEFAULT AS IDENTITY,
            TASK_ID         NUMBER NOT NULL,
            SKILL_ID        NUMBER NOT NULL,
            REQUIRED_LEVEL  NUMBER(1),
            SOURCE          VARCHAR2(10 CHAR) DEFAULT ''MANUAL'' NOT NULL,
            CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT PK_TASK_REQUIRED_SKILLS PRIMARY KEY (ID),
            CONSTRAINT UQ_TASK_REQ_SKILL UNIQUE (TASK_ID, SKILL_ID),
            CONSTRAINT FK_TASK_REQ_SKILLS_TASK FOREIGN KEY (TASK_ID)
                REFERENCES TASKS(ID) ON DELETE CASCADE,
            CONSTRAINT FK_TASK_REQ_SKILLS_SKILL FOREIGN KEY (SKILL_ID)
                REFERENCES SKILLS(ID),
            CONSTRAINT CK_TASK_REQ_LEVEL CHECK
                (REQUIRED_LEVEL IS NULL OR REQUIRED_LEVEL BETWEEN 1 AND 5),
            CONSTRAINT CK_TASK_REQ_SOURCE CHECK (SOURCE IN (''AI'', ''MANUAL''))
        )');
    -- UQ_TASK_REQ_SKILL bắt đầu bằng TASK_ID nên đã kiêm index cho khoá ngoại TASK_ID
    chay('CREATE INDEX IDX_TASK_REQ_SKILLS_SKILL_ID ON TASK_REQUIRED_SKILLS (SKILL_ID)');

    ----------------------------------------------------------------------------
    -- 4. USERS — nhóm và ngày vào làm
    --
    -- Một index (TEAM_ID, DEPARTMENT_ID) phục vụ được cả hai khoá ngoại: Oracle chỉ
    -- cần các cột khoá ngoại nằm ở đầu index, không cần đúng thứ tự.
    ----------------------------------------------------------------------------
    chay('ALTER TABLE USERS ADD (TEAM_ID NUMBER)');
    chay('ALTER TABLE USERS ADD (HIRED_DATE DATE)');
    chay('ALTER TABLE USERS ADD CONSTRAINT FK_USERS_TEAM
              FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(ID)');
    chay('ALTER TABLE USERS ADD CONSTRAINT FK_USERS_TEAM_DEPT
              FOREIGN KEY (DEPARTMENT_ID, TEAM_ID) REFERENCES TEAMS(DEPARTMENT_ID, ID)');
    chay('CREATE INDEX IDX_USERS_TEAM_DEPT ON USERS (TEAM_ID, DEPARTMENT_ID)');

    ----------------------------------------------------------------------------
    -- 5. USER_SKILLS — trỏ về danh mục chuẩn, thêm số năm kinh nghiệm
    --
    -- SKILL_ID tạm cho phép NULL và CHƯA có ràng buộc duy nhất (USER_ID, SKILL_ID).
    -- Lý do: script 21 nạp kỹ năng chỉ bằng tên, SKILL_ID được 24 điền sau. Nếu thêm
    -- ràng buộc duy nhất ngay, Oracle coi hai dòng (5, NULL) là trùng nhau và 21 sẽ
    -- hỏng từ dòng thứ hai. Hai việc này làm ở bước thu hẹp, khi bỏ hẳn SKILL_NAME.
    ----------------------------------------------------------------------------
    chay('ALTER TABLE USER_SKILLS ADD (SKILL_ID NUMBER)');
    chay('ALTER TABLE USER_SKILLS ADD (YEARS_EXPERIENCE NUMBER(3,1))');
    chay('ALTER TABLE USER_SKILLS ADD CONSTRAINT FK_USER_SKILLS_SKILL
              FOREIGN KEY (SKILL_ID) REFERENCES SKILLS(ID)');
    chay('ALTER TABLE USER_SKILLS ADD CONSTRAINT CK_USER_SKILLS_YEARS
              CHECK (YEARS_EXPERIENCE IS NULL OR YEARS_EXPERIENCE BETWEEN 0 AND 60)');
    chay('CREATE INDEX IDX_USER_SKILLS_SKILL_ID ON USER_SKILLS (SKILL_ID)');

    ----------------------------------------------------------------------------
    -- 6. TASKS — nhóm phụ trách và ước lượng công sức (giờ công)
    ----------------------------------------------------------------------------
    chay('ALTER TABLE TASKS ADD (TEAM_ID NUMBER)');
    chay('ALTER TABLE TASKS ADD (ESTIMATED_EFFORT NUMBER(5,1))');
    chay('ALTER TABLE TASKS ADD CONSTRAINT FK_TASKS_TEAM
              FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(ID)');
    chay('ALTER TABLE TASKS ADD CONSTRAINT FK_TASKS_TEAM_DEPT
              FOREIGN KEY (DEPARTMENT_ID, TEAM_ID) REFERENCES TEAMS(DEPARTMENT_ID, ID)');
    chay('ALTER TABLE TASKS ADD CONSTRAINT CK_TASKS_EFFORT
              CHECK (ESTIMATED_EFFORT IS NULL OR ESTIMATED_EFFORT > 0)');
    chay('CREATE INDEX IDX_TASKS_TEAM_DEPT ON TASKS (TEAM_ID, DEPARTMENT_ID)');

    ----------------------------------------------------------------------------
    -- 7. TASK_REPORTS — điểm đánh giá, thang 1..5
    --
    -- Thêm hai cột vào đây thay vì tạo bảng TASK_EVALUATIONS riêng: bảng này đã có
    -- sẵn REVIEWER_ID, REVIEWED_AT, REVIEW_NOTE — tạo bảng mới là lặp ba trường.
    --
    -- Thang 1..5 chứ không phải 0..100: người chấm không phân biệt nổi 73 với 76,
    -- thang rộng chỉ tạo độ chính xác giả. Công thức chấm điểm tự quy về 0..1.
    --
    -- Báo cáo đang chờ duyệt thì chưa ai chấm, nên không được có điểm.
    ----------------------------------------------------------------------------
    chay('ALTER TABLE TASK_REPORTS ADD (QUALITY_SCORE NUMBER(1))');
    chay('ALTER TABLE TASK_REPORTS ADD (COMPLETION_SCORE NUMBER(1))');
    chay('ALTER TABLE TASK_REPORTS ADD CONSTRAINT CK_TASK_REPORTS_QUALITY
              CHECK (QUALITY_SCORE IS NULL OR QUALITY_SCORE BETWEEN 1 AND 5)');
    chay('ALTER TABLE TASK_REPORTS ADD CONSTRAINT CK_TASK_REPORTS_COMPLETION
              CHECK (COMPLETION_SCORE IS NULL OR COMPLETION_SCORE BETWEEN 1 AND 5)');
    chay('ALTER TABLE TASK_REPORTS ADD CONSTRAINT CK_TASK_REPORTS_SCORE_REVIEWED
              CHECK (REPORT_STATUS <> ''CHO_XAC_NHAN''
                     OR (QUALITY_SCORE IS NULL AND COMPLETION_SCORE IS NULL))');

    ----------------------------------------------------------------------------
    -- 8. DEPARTMENTS — trưởng phòng
    --
    -- Tạo vòng tham chiếu với USERS.DEPARTMENT_ID. Oracle chấp nhận vì cả hai cột đều
    -- cho phép NULL; script nạp dữ liệu phải chèn phòng trước, người sau, rồi mới cập
    -- nhật ngược HEAD_USER_ID.
    ----------------------------------------------------------------------------
    chay('ALTER TABLE DEPARTMENTS ADD (HEAD_USER_ID NUMBER)');
    chay('ALTER TABLE DEPARTMENTS ADD CONSTRAINT FK_DEPARTMENTS_HEAD
              FOREIGN KEY (HEAD_USER_ID) REFERENCES USERS(ID) ON DELETE SET NULL');
    chay('CREATE INDEX IDX_DEPARTMENTS_HEAD_USER_ID ON DEPARTMENTS (HEAD_USER_ID)');
END;
/

--==============================================================================
-- 9. Bỏ giá trị cũ MANAGER khỏi CK_USERS_ROLE
--
-- Script 20 để lại MANAGER cho dữ liệu cũ khỏi vỡ giữa chừng. Script 21 đã chuyển
-- hết sang bốn giá trị mới nên giờ bỏ được. Kiểm tra trước cho chắc.
--==============================================================================
DECLARE
    v_dem NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_dem FROM USERS
    WHERE  USER_ROLE NOT IN ('DIRECTOR', 'DEPT_HEAD', 'TEAM_LEAD', 'EMPLOYEE');

    IF v_dem > 0 THEN
        RAISE_APPLICATION_ERROR(-20001,
            'Còn ' || v_dem || ' người dùng mang vai trò cũ, chưa bỏ được MANAGER.');
    END IF;

    SELECT COUNT(*) INTO v_dem FROM USER_CONSTRAINTS
    WHERE  TABLE_NAME = 'USERS' AND CONSTRAINT_NAME = 'CK_USERS_ROLE';

    IF v_dem > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE USERS DROP CONSTRAINT CK_USERS_ROLE';
    END IF;

    EXECUTE IMMEDIATE '
        ALTER TABLE USERS ADD CONSTRAINT CK_USERS_ROLE CHECK (
            USER_ROLE IN (''DIRECTOR'', ''DEPT_HEAD'', ''TEAM_LEAD'', ''EMPLOYEE'')
        )';
END;
/

COMMIT;

--==============================================================================
-- KIỂM CHỨNG
--==============================================================================
SET PAGESIZE 200 LINESIZE 200
SET FEEDBACK OFF
COLUMN TABLE_NAME FORMAT A22
COLUMN COLUMN_NAME FORMAT A20
COLUMN CONSTRAINT_NAME FORMAT A32

PROMPT
PROMPT === Bảng mới ===
SELECT TABLE_NAME FROM USER_TABLES
WHERE  TABLE_NAME IN ('TEAMS', 'SKILLS', 'TASK_REQUIRED_SKILLS') ORDER BY 1;

PROMPT
PROMPT === Cột mới ===
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, NULLABLE
FROM   USER_TAB_COLUMNS
WHERE  (TABLE_NAME, COLUMN_NAME) IN (
          ('USERS', 'TEAM_ID'), ('USERS', 'HIRED_DATE'),
          ('USER_SKILLS', 'SKILL_ID'), ('USER_SKILLS', 'YEARS_EXPERIENCE'),
          ('TASKS', 'TEAM_ID'), ('TASKS', 'ESTIMATED_EFFORT'),
          ('TASK_REPORTS', 'QUALITY_SCORE'), ('TASK_REPORTS', 'COMPLETION_SCORE'),
          ('DEPARTMENTS', 'HEAD_USER_ID'))
ORDER  BY 1, 2;

PROMPT
PROMPT === Khoá ngoại mới ===
SELECT TABLE_NAME, CONSTRAINT_NAME, DELETE_RULE
FROM   USER_CONSTRAINTS
WHERE  CONSTRAINT_TYPE = 'R'
  AND  CONSTRAINT_NAME IN ('FK_TEAMS_DEPARTMENT', 'FK_TEAMS_LEADER',
         'FK_TASK_REQ_SKILLS_TASK', 'FK_TASK_REQ_SKILLS_SKILL',
         'FK_USERS_TEAM', 'FK_USERS_TEAM_DEPT', 'FK_USER_SKILLS_SKILL',
         'FK_TASKS_TEAM', 'FK_TASKS_TEAM_DEPT', 'FK_DEPARTMENTS_HEAD')
ORDER  BY 1, 2;

PROMPT
PROMPT === Ràng buộc vai trò ===
SELECT SEARCH_CONDITION_VC FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CK_USERS_ROLE';

PROMPT
PROMPT === Dữ liệu cũ còn nguyên ===
SELECT 'USERS=' || (SELECT COUNT(*) FROM USERS) ||
       ' USER_SKILLS=' || (SELECT COUNT(*) FROM USER_SKILLS) ||
       ' TASKS=' || (SELECT COUNT(*) FROM TASKS) ||
       ' TASK_REPORTS=' || (SELECT COUNT(*) FROM TASK_REPORTS) AS CON_NGUYEN
FROM DUAL;
