namespace TaskApp.Api.Entities;

/// <summary>
/// Bang USERS - tai khoan va vai tro nguoi dung.
/// </summary>
public class User : IAuditable
{
    /// <summary>Cot ID - khoa chinh, Oracle NUMBER GENERATED BY DEFAULT AS IDENTITY.</summary>
    public long Id { get; set; }

    /// <summary>Cot USERNAME - ten dang nhap, duy nhat toan he thong.</summary>
    public string Username { get; set; } = string.Empty;

    /// <summary>Cot PASSWORD_HASH - chuoi bam BCrypt, KHONG bao gio la mat khau ro.</summary>
    public string PasswordHash { get; set; } = string.Empty;

    /// <summary>Cot FULL_NAME - ho ten day du, co dau tieng Viet.</summary>
    public string FullName { get; set; } = string.Empty;

    /// <summary>Cot EMAIL - dia chi thu dien tu, cho phep rong.</summary>
    public string? Email { get; set; }

    /// <summary>Cot ROLE - xem <see cref="Common.VaiTro"/>: MANAGER hoac EMPLOYEE.</summary>
    public string Role { get; set; } = string.Empty;

    /// <summary>Cot STATUS - xem <see cref="Common.TrangThaiNguoiDung"/>: ACTIVE hoac INACTIVE.</summary>
    public string Status { get; set; } = string.Empty;

    /// <summary>Cot CREATED_AT.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>Cot UPDATED_AT.</summary>
    public DateTime UpdatedAt { get; set; }

    // ----- Navigation property -----

    /// <summary>Danh sach ky nang cua nguoi dung (USER_SKILLS.USER_ID).</summary>
    public ICollection<UserSkill> Skills { get; set; } = new List<UserSkill>();

    /// <summary>Cac nhiem vu do nguoi nay tao/giao (TASKS.CREATOR_ID).</summary>
    public ICollection<TaskItem> NhiemVuDaTao { get; set; } = new List<TaskItem>();

    /// <summary>Cac nhiem vu duoc giao cho nguoi nay (TASKS.ASSIGNEE_ID).</summary>
    public ICollection<TaskItem> NhiemVuDuocGiao { get; set; } = new List<TaskItem>();

    /// <summary>Cac lan cap nhat tien do do nguoi nay ghi (TASK_PROGRESS.USER_ID).</summary>
    public ICollection<TaskProgress> CapNhatTienDo { get; set; } = new List<TaskProgress>();

    /// <summary>Cac bao cao do nguoi nay gui (TASK_REPORTS.REPORTER_ID).</summary>
    public ICollection<TaskReport> BaoCaoDaGui { get; set; } = new List<TaskReport>();

    /// <summary>Cac bao cao do nguoi nay duyet (TASK_REPORTS.REVIEWER_ID).</summary>
    public ICollection<TaskReport> BaoCaoDaDuyet { get; set; } = new List<TaskReport>();

    /// <summary>Cac tep do nguoi nay tai len (TASK_ATTACHMENTS.UPLOADED_BY).</summary>
    public ICollection<TaskAttachment> TepDaTaiLen { get; set; } = new List<TaskAttachment>();
}
