--------------------------------------------------------------------------------
-- 01_tao_bang.sql
-- Muc dich : Tao 7 bang nghiep vu cua mini app Quan ly nhiem vu.
-- Nguon    : DATABASE_SOURCE_OF_TRUTH_TASK_MANAGEMENT.md (muc 5 va muc 12).
-- Chay bang: chinh tai khoan TASK_APP.
--            sqlplus TASK_APP/<mat_khau>@127.0.0.1:1521/XEPDB1 @01_tao_bang.sql
--
-- DIEM KHAC voi DDL trong tai lieu goc:
--   Moi cot chuoi CO THE chua tieng Viet duoc khai VARCHAR2(n CHAR) thay vi VARCHAR2(n).
--   Ly do: Oracle mac dinh NLS_LENGTH_SEMANTICS = BYTE; trong AL32UTF8 mot ky tu tieng Viet
--   co dau chiem toi 3 byte, nen VARCHAR2(100) chi chua duoc ~33 ky tu roi bao ORA-12899.
--   Cac cot chi chua ASCII (USERNAME, ROLE, STATUS, PRIORITY, STATUS_CODE, PASSWORD_HASH...)
--   cung de CHAR cho dong nhat, khong gay hai.
--
-- Script chay lai duoc nhieu lan: moi lenh CREATE boc trong khoi PL/SQL bo qua
--   ORA-00955 (name is already used by an existing object)
--   ORA-01408 (such column list already indexed)
--
-- Thu tu phu thuoc khoa ngoai:
--   USERS -> USER_SKILLS
--   TASK_STATUS_LOOKUP -> TASKS -> TASK_PROGRESS / TASK_REPORTS -> TASK_ATTACHMENTS
--------------------------------------------------------------------------------

--==============================================================================
-- 1. USERS - tai khoan va vai tro nguoi dung
--==============================================================================
BEGIN
    EXECUTE IMMEDIATE q'[
CREATE TABLE USERS (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME        VARCHAR2(50 CHAR)   NOT NULL,
    PASSWORD_HASH   VARCHAR2(255 CHAR)  NOT NULL,
    FULL_NAME       VARCHAR2(100 CHAR)  NOT NULL,
    EMAIL           VARCHAR2(100 CHAR),
    ROLE            VARCHAR2(20 CHAR)   NOT NULL,
    STATUS          VARCHAR2(20 CHAR)   DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT      TIMESTAMP           DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP           DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME),

    CONSTRAINT CK_USERS_ROLE
        CHECK (ROLE IN ('MANAGER', 'EMPLOYEE')),

    CONSTRAINT CK_USERS_STATUS
        CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
)]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

--==============================================================================
-- 2. USER_SKILLS - ky nang/chuyen mon, du lieu dau vao cho AI goi y nguoi thuc hien
--==============================================================================
BEGIN
    EXECUTE IMMEDIATE q'[
CREATE TABLE USER_SKILLS (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID         NUMBER              NOT NULL,
    SKILL_NAME      VARCHAR2(100 CHAR)  NOT NULL,
    SKILL_LEVEL     NUMBER(1),
    DESCRIPTION     VARCHAR2(500 CHAR),
    CREATED_AT      TIMESTAMP           DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP           DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_USER_SKILLS_USER
        FOREIGN KEY (USER_ID) REFERENCES USERS(ID),

    CONSTRAINT CK_USER_SKILL_LEVEL
        CHECK (SKILL_LEVEL BETWEEN 1 AND 5),

    CONSTRAINT UQ_USER_SKILL UNIQUE (USER_ID, SKILL_NAME)
)]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

--==============================================================================
-- 3. TASK_STATUS_LOOKUP - danh muc trang thai cua NHIEM VU
--    Trang thai BAO CAO nam rieng o TASK_REPORTS.STATUS, khong tron hai co che.
--==============================================================================
BEGIN
    EXECUTE IMMEDIATE q'[
CREATE TABLE TASK_STATUS_LOOKUP (
    CODE            VARCHAR2(30 CHAR)   PRIMARY KEY,
    NAME            VARCHAR2(100 CHAR)  NOT NULL,
    DESCRIPTION     VARCHAR2(255 CHAR),
    SORT_ORDER      NUMBER
)]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

--==============================================================================
-- 4. TASKS - bang trung tam
--    Hai khoa ngoai cung tro ve USERS: CREATOR_ID (nguoi giao) va ASSIGNEE_ID (nguoi lam).
--    ASSIGNEE_ID nullable vi nhiem vu o trang thai MOI_TAO chua co nguoi thuc hien.
--==============================================================================
BEGIN
    EXECUTE IMMEDIATE q'[
CREATE TABLE TASKS (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TITLE           VARCHAR2(200 CHAR)  NOT NULL,
    DESCRIPTION     CLOB,
    CREATOR_ID      NUMBER              NOT NULL,
    ASSIGNEE_ID     NUMBER,
    PRIORITY        VARCHAR2(20 CHAR)   DEFAULT 'MEDIUM' NOT NULL,
    STATUS_CODE     VARCHAR2(30 CHAR)   DEFAULT 'MOI_TAO' NOT NULL,
    START_DATE      DATE,
    DUE_DATE        DATE,
    CREATED_AT      TIMESTAMP           DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP           DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_TASK_CREATOR
        FOREIGN KEY (CREATOR_ID) REFERENCES USERS(ID),

    CONSTRAINT FK_TASK_ASSIGNEE
        FOREIGN KEY (ASSIGNEE_ID) REFERENCES USERS(ID),

    CONSTRAINT FK_TASK_STATUS
        FOREIGN KEY (STATUS_CODE) REFERENCES TASK_STATUS_LOOKUP(CODE),

    CONSTRAINT CK_TASK_PRIORITY
        CHECK (PRIORITY IN ('LOW', 'MEDIUM', 'HIGH')),

    CONSTRAINT CK_TASK_DATES
        CHECK (
            DUE_DATE IS NULL
            OR START_DATE IS NULL
            OR DUE_DATE >= START_DATE
        )
)]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

--==============================================================================
-- 5. TASK_PROGRESS - lich su cap nhat tien do (khong ghi de, moi lan mot dong)
--==============================================================================
BEGIN
    EXECUTE IMMEDIATE q'[
CREATE TABLE TASK_PROGRESS (
    ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TASK_ID             NUMBER              NOT NULL,
    USER_ID             NUMBER              NOT NULL,
    PROGRESS_PERCENT    NUMBER(3)           NOT NULL,
    CONTENT             VARCHAR2(2000 CHAR),
    CREATED_AT          TIMESTAMP           DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_PROGRESS_TASK
        FOREIGN KEY (TASK_ID) REFERENCES TASKS(ID),

    CONSTRAINT FK_PROGRESS_USER
        FOREIGN KEY (USER_ID) REFERENCES USERS(ID),

    CONSTRAINT CK_PROGRESS_PERCENT
        CHECK (PROGRESS_PERCENT BETWEEN 0 AND 100)
)]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

--==============================================================================
-- 6. TASK_REPORTS - bao cao ket qua va qua trinh nguoi giao xac nhan/tu choi
--    Hai khoa ngoai cung tro ve USERS: REPORTER_ID va REVIEWER_ID (nullable).
--==============================================================================
BEGIN
    EXECUTE IMMEDIATE q'[
CREATE TABLE TASK_REPORTS (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TASK_ID         NUMBER              NOT NULL,
    REPORTER_ID     NUMBER              NOT NULL,
    CONTENT         CLOB                NOT NULL,
    STATUS          VARCHAR2(30 CHAR)   DEFAULT 'CHO_XAC_NHAN' NOT NULL,
    REVIEWER_ID     NUMBER,
    REVIEW_NOTE     CLOB,
    CREATED_AT      TIMESTAMP           DEFAULT CURRENT_TIMESTAMP,
    REVIEWED_AT     TIMESTAMP,

    CONSTRAINT FK_REPORT_TASK
        FOREIGN KEY (TASK_ID) REFERENCES TASKS(ID),

    CONSTRAINT FK_REPORT_REPORTER
        FOREIGN KEY (REPORTER_ID) REFERENCES USERS(ID),

    CONSTRAINT FK_REPORT_REVIEWER
        FOREIGN KEY (REVIEWER_ID) REFERENCES USERS(ID),

    CONSTRAINT CK_REPORT_STATUS
        CHECK (STATUS IN ('CHO_XAC_NHAN', 'DA_XAC_NHAN', 'TU_CHOI'))
)]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

--==============================================================================
-- 7. TASK_ATTACHMENTS - metadata tep dinh kem (khong luu binary trong DB)
--    REPORT_ID NULL       => tep dinh kem truc tiep cho nhiem vu
--    REPORT_ID co gia tri => tep la tai lieu cua mot bao cao
--    KHONG co quan he nao giua TASK_ATTACHMENTS va TASK_STATUS_LOOKUP.
--==============================================================================
BEGIN
    EXECUTE IMMEDIATE q'[
CREATE TABLE TASK_ATTACHMENTS (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TASK_ID         NUMBER              NOT NULL,
    REPORT_ID       NUMBER,
    FILE_NAME       VARCHAR2(255 CHAR)  NOT NULL,
    FILE_PATH       VARCHAR2(500 CHAR)  NOT NULL,
    FILE_TYPE       VARCHAR2(100 CHAR),
    FILE_SIZE       NUMBER,
    UPLOADED_BY     NUMBER              NOT NULL,
    UPLOADED_AT     TIMESTAMP           DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_ATTACHMENT_TASK
        FOREIGN KEY (TASK_ID) REFERENCES TASKS(ID),

    CONSTRAINT FK_ATTACHMENT_REPORT
        FOREIGN KEY (REPORT_ID) REFERENCES TASK_REPORTS(ID),

    CONSTRAINT FK_ATTACHMENT_USER
        FOREIGN KEY (UPLOADED_BY) REFERENCES USERS(ID)
)]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

--==============================================================================
-- 8. Index cho cac cot hay dung de loc / join
--    Oracle tu tao index cho PRIMARY KEY va UNIQUE nen chi bo sung cho khoa ngoai
--    va cac cot loc thuong xuyen.
--==============================================================================
DECLARE
    TYPE t_danh_sach IS TABLE OF VARCHAR2(500);
    v_lenh t_danh_sach := t_danh_sach(
        'CREATE INDEX IX_TASKS_ASSIGNEE   ON TASKS(ASSIGNEE_ID)',
        'CREATE INDEX IX_TASKS_CREATOR    ON TASKS(CREATOR_ID)',
        'CREATE INDEX IX_TASKS_STATUS     ON TASKS(STATUS_CODE)',
        'CREATE INDEX IX_TASKS_DUE_DATE   ON TASKS(DUE_DATE)',
        'CREATE INDEX IX_PROGRESS_TASK    ON TASK_PROGRESS(TASK_ID)',
        'CREATE INDEX IX_PROGRESS_USER    ON TASK_PROGRESS(USER_ID)',
        'CREATE INDEX IX_REPORTS_TASK     ON TASK_REPORTS(TASK_ID)',
        'CREATE INDEX IX_REPORTS_REPORTER ON TASK_REPORTS(REPORTER_ID)',
        'CREATE INDEX IX_REPORTS_REVIEWER ON TASK_REPORTS(REVIEWER_ID)',
        'CREATE INDEX IX_REPORTS_STATUS   ON TASK_REPORTS(STATUS)',
        'CREATE INDEX IX_ATTACH_TASK      ON TASK_ATTACHMENTS(TASK_ID)',
        'CREATE INDEX IX_ATTACH_REPORT    ON TASK_ATTACHMENTS(REPORT_ID)',
        'CREATE INDEX IX_ATTACH_UPLOADER  ON TASK_ATTACHMENTS(UPLOADED_BY)',
        'CREATE INDEX IX_USER_SKILLS_USER ON USER_SKILLS(USER_ID)',
        'CREATE INDEX IX_USER_SKILLS_NAME ON USER_SKILLS(SKILL_NAME)'
    );
BEGIN
    FOR i IN 1 .. v_lenh.COUNT LOOP
        BEGIN
            EXECUTE IMMEDIATE v_lenh(i);
        EXCEPTION
            WHEN OTHERS THEN
                -- -955  : ten index da ton tai
                -- -1408 : danh sach cot da duoc danh index (thuong do UNIQUE constraint)
                IF SQLCODE != -955 AND SQLCODE != -1408 THEN
                    RAISE;
                END IF;
        END;
    END LOOP;
END;
/

--==============================================================================
-- 9. Chu thich bang (COMMENT chay lai nhieu lan khong loi)
--==============================================================================
COMMENT ON TABLE USERS              IS 'Tai khoan nguoi dung: MANAGER giao viec, EMPLOYEE thuc hien';
COMMENT ON TABLE USER_SKILLS        IS 'Ky nang/chuyen mon cua nguoi dung, phuc vu AI goi y nguoi thuc hien';
COMMENT ON TABLE TASK_STATUS_LOOKUP IS 'Danh muc trang thai cua nhiem vu';
COMMENT ON TABLE TASKS              IS 'Nhiem vu - bang trung tam cua he thong';
COMMENT ON TABLE TASK_PROGRESS      IS 'Lich su cap nhat tien do cua nhiem vu';
COMMENT ON TABLE TASK_REPORTS       IS 'Bao cao ket qua va ket luan xac nhan/tu choi';
COMMENT ON TABLE TASK_ATTACHMENTS   IS 'Metadata tep dinh kem cua nhiem vu hoac cua bao cao';

COMMIT;

--==============================================================================
-- 10. Kiem chung: phai thay du 7 bang
--==============================================================================
SELECT TABLE_NAME
FROM   USER_TABLES
WHERE  TABLE_NAME IN ('USERS', 'USER_SKILLS', 'TASK_STATUS_LOOKUP',
                      'TASKS', 'TASK_PROGRESS', 'TASK_REPORTS', 'TASK_ATTACHMENTS')
ORDER  BY TABLE_NAME;
